"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as descriptor
from google.protobuf import message as message
import typing as typing

DESCRIPTOR: descriptor.FileDescriptor

@typing.final

Empty: Empty

class Empty(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
